const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("wasend", {
  getConnection: () => ipcRenderer.invoke("whatsapp:status"),
  connect: () => ipcRenderer.invoke("whatsapp:connect"),
  disconnect: () => ipcRenderer.invoke("whatsapp:disconnect"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  listContacts: () => ipcRenderer.invoke("contacts:list"),
  addContact: (contact) => ipcRenderer.invoke("contacts:add", contact),
  removeContact: (id) => ipcRenderer.invoke("contacts:remove", id),
  importContacts: (payload) => ipcRenderer.invoke("contacts:import", payload),
  importContactFile: () => ipcRenderer.invoke("contacts:import-file"),
  exportContacts: () => ipcRenderer.invoke("contacts:export"),
  listGroups: () => ipcRenderer.invoke("groups:list"),
  createGroup: (name) => ipcRenderer.invoke("groups:create", name),
  listTemplates: () => ipcRenderer.invoke("templates:list"),
  saveTemplate: (template) => ipcRenderer.invoke("templates:save", template),
  removeTemplate: (id) => ipcRenderer.invoke("templates:remove", id),
  duplicateTemplate: (id) => ipcRenderer.invoke("templates:duplicate", id),
  listCampaigns: () => ipcRenderer.invoke("campaigns:list"),
  getDashboardSummary: () => ipcRenderer.invoke("dashboard:summary"),
  createCampaign: (campaign) => ipcRenderer.invoke("campaigns:create", campaign),
  startCampaign: (id) => ipcRenderer.invoke("campaigns:start", id),
  resumeCampaign: (id) => ipcRenderer.invoke("campaigns:resume", id),
  pauseCampaign: (id) => ipcRenderer.invoke("campaigns:pause", id),
  stopCampaign: (id) => ipcRenderer.invoke("campaigns:stop", id),
  duplicateCampaign: (id) => ipcRenderer.invoke("campaigns:duplicate", id),
  removeCampaign: (id) => ipcRenderer.invoke("campaigns:remove", id),
  listCampaignLogs: (id) => ipcRenderer.invoke("campaigns:logs", id),
  listMedia: () => ipcRenderer.invoke("media:list"),
  addMedia: () => ipcRenderer.invoke("media:add"),
  removeMedia: (id) => ipcRenderer.invoke("media:remove", id),
  listBlacklist: () => ipcRenderer.invoke("blacklist:list"),
  addBlacklist: (phone, reason) => ipcRenderer.invoke("blacklist:add", phone, reason),
  removeBlacklist: (id) => ipcRenderer.invoke("blacklist:remove", id),
  exportReportCsv: (id) => ipcRenderer.invoke("reports:csv", id),
  exportReportPdf: () => ipcRenderer.invoke("reports:pdf"),
  resetApp: () => ipcRenderer.invoke("app:reset"),
  onConnection: (callback) => ipcRenderer.on("whatsapp:status", (_event, value) => callback(value)),
  offConnection: () => ipcRenderer.removeAllListeners("whatsapp:status"),
  onCampaignProgress: (callback) => ipcRenderer.on("campaign:progress", (_event, value) => callback(value)),
  offCampaignProgress: () => ipcRenderer.removeAllListeners("campaign:progress"),
});
